### ISSUE TITLE
JUST FOR A QUESTION

### ISSUE THREAD

**Issue by csh0101** [adamchalmers/rust-club-html-parser#1]
https://www.youtube.com/watch?v=LUcI6KkM-PE&t=2329s 
 I Hello, I would like to ask whether the code in Section 2 or the new version of CKL's parser will eventually be put on GITHUB in an open source form.

**Comment by adamchalmers** [comment]
Hi! It absolutely is. One sec.

**Comment by adamchalmers** [comment]
Hi! Yes it's all open sourced here: 

https://github.com/kittycad/modeling-app/tree/main/src%2Fwasm-lib%2Fkcl%2Fsrc 

Tokenizer and parser are in separate modules.

**Comment by csh0101** [comment]
> Hi! Yes it's all open sourced here:你好！是的，这里都是开源的：
> 
> https://github.com/kittycad/modeling-app/tree/main/src%2Fwasm-lib%2Fkcl%2Fsrc
> 
> Tokenizer and parser are in separate modules.分词器和解析器位于不同的模块中。

Everything is Good!
