### ISSUE TITLE
Just Some Suggestions I Found!

### ISSUE THREAD

**Issue by csh0101** [adamchalmers/rust-club-html-parser#2]
just! I 'm a noob for Rust.
and I'm watching the youtube the Rust Club video.

And I find somethin for fix this ? myabe? 

```rust
               let fx_hash_builder = BuildHasherDefault::<FxHasher>::default();
        let mut hash_map: HashMap<&str, &str, _> = HashMap::with_hasher(fx_hash_builder);
        hash_map.extend([("width", "40"), ("height", "30")]);
        let expected = Tag {
            tag_type: "div",
            attributes: Attributes { kvs: hash_map },
        };
```

**Comment by csh0101** [comment]
I just mean maybe use with function with_hasher,  which can help us to avoid iter().collet(). I think it's need the extra cost, if the compile dont optimizate the code line

**Comment by csh0101** [comment]
@adamchalmers  what do you think of my opinion!

**Comment by adamchalmers** [comment]
Hi! The reason I couldn't use the Fx hashmap, hash function etc was that Winnow only supported accumulating parsed results into the standard Rust hashmap/hasher. But new releases of Winnow do support it. So now we can move forward with the faster HashMap just fine :)

**Comment by csh0101** [comment]
> Hi! The reason I couldn't use the Fx hashmap, hash function etc was that Winnow only supported accumulating parsed results into the standard Rust hashmap/hasher. But new releases of Winnow do support it. So now we can move forward with the faster HashMap just fine :)你好！我无法使用 Fx hashmap、哈希函数等的原因是 Winnow 仅支持将解析结果累积到标准 Rust hashmap/hasher 中。但新版本的 Winnow 确实支持它。所以现在我们可以继续使用更快的 HashMap 了:)

Yeah You' are Right .. And I 'm sure . when I seeing the youtube video., the winnow has supported it!
